package com.example.handphoneapp.model

import com.example.handphoneapp.R

object HandPhoneDataSource {
    val handPhone = listOf(
        HandPhone("1", R.drawable.redmi_note_12_1, "Redmi Note 12",
            "Redmi Note 12 menjadi hp terbaru 2023 yang paling anyar di Indonesia. Rilis April tahun ini, hp Redmi ini mengusung layar AMOLED dengan resolusi Full HD+ dan refresh rate 120Hz. Yang hobi foto, Redmi Note 12 menawarkan kamera utama 50 MP, kamera ultrawide 8 MP dan kamera macro 2 MP. Sedangkan di bagian depan ada kamera selfie 13 MP. Hasil fotonya bisa kamu simpan di dalam memori internal yang memiliki kapasitas sebesar 128 GB dengan opsi perluasan hingga 1 TB menggunakan microSD. Performanya ditenagai prosesor Snapdragon 685 yang dipadukan dengan pilihan RAM 4 GB, 6 GB dan 8 GB. Ada pula dukungan fitur untuk memperbesar memori RAM hingga 5 GB. Untuk sumber daya menggunakan baterai 5.000 mAh dengan dukungan fast charging 33W. Jika tertarik, harga Redmi Note 12 versi RAM 4GB/128 GB) dibanderol Rp 2.599.000. Lalu harga Redmi Note 12 RAM 6 GB/128 GB di jual Rp 2.799.000 dan Redmi Note 12 versi RAM 8 GB/128 GB dipasarakan Rp 2.999.000."),
        HandPhone("2", R.drawable.redmi_note_12, "Redmi Note 12 Pro 5G",
            "Diluncurkan bersamaan, tambahan ‘Pro 5G’ di bagian belakang ingin menegaskan perbedaan dengan Redmi Note 12 versi standar. Yang pasti spesifikasinya lebih baik. Lihat saja layarnya yang menggunakan panel P-OLED seluas 6,67 inci, resolusi Full HD+ serta refresh rate 120Hz. Konfigurasi ini tentu membuat layarnya sangat responsif dalam menerima perintah. Di sektor fotografi, kamera Redmi Note 12 Pro 5G juga memiliki resolusi yang sama yaitu 50 MP, bedanya hp ini menggunakan sensor Sony IMX766. Kamera utama ini masih akan di dukung sensor ultrawide 8 MP dan makro 2 MP. Ada juga fitur OIS yang memungkinkan kamu untuk melakukan perekaman video lebih stabil. Sementara kamera depannya masih cukup bisa diandalkan dengan resolusi 16 MP. Performa Redmi Note 12 Pro 5G ditenagai prosesor MediaTek Dimensity 1080 (fabrikasi 6nm) dengan sokongan RAM 8 GB yang dapat diperluas hingga 13 GB serta ruang penyimpanan internal  256 GB. Hp ini menanam baterai 5.000 mAh dengan dukungan fast charging 67W. Harga Redmi Note 12 Pro 5G dibanderol Rp 4.599.000."),
        HandPhone("3", R.drawable.vivo_v27_5g, "Vivo V27 5G",
            "Hp ini mengusung layar melengkung (curved) berjenis AMOLED seluas 6.78 inci, resolusi Full HD+ dan refresh rate 120 Hz. Pada bagian atas layar terdapat punch hole yang didalamnya terpasang kamera depan beresolusi 50 MP. Dengan resolusi tersebut pastinya hasil foto selfie akan berkualitas tinggi. Lalu dibagian belakang ada tiga kamera yang terdiri dari sensor utama 50 MP (sensor Sony), ultrawide 8 MP dan makro 2 MP yang masih bisa diandalkan untuk mengabadikan momen pribadi. Performa vivo V27 5G ditenagai chipset MediaTek Dimensity 7200 yang disokong RAM 8 GB dan penyimpanan internal 256 GB. Hp vivo ini mengandalkan baterai berkapasitas 4.600mAH dan mendukung fast charging 66 watt."),
        HandPhone("4", R.drawable.vivo_v27e, "Vivo V27e",
            "Beda dari versi 5G, vivo V27e menggunakan layar datar (flat) dengan rukuran yang lebih kecil yaitu 6,62 inci. Meski demikian masih menggunakan panel AMOLED, resolusi Full HD+ dan refresh rate 120 Hz. Sedangkan kamera selfie sedikit lebih kecil dengan resolusi 32 MP. Kemudian kamera belakangnya terdiri dari sensor utama 64 MP, bokeh 2 MP dan makro 2 MP. Vivo V27e ditenagai prosesor MediaTek Helio G99 yang ditunjang memori RAM 8 GB dan memori internal 256 GB serta RAM 12 GB dan memori internal 256 GB. Soal sumber daya, hp vivo ini ditopang baterai berkapasitas 4.600mAH dan fast charging 66 watt."),
        HandPhone("5", R.drawable.samsung_galaxy_a34_5g, "Samsung Galaxy A34 5G",
            "Pilihan hp terbaru 2023 berikutnya ada Samsung Galaxy A34 5G yang rilis bulan Maret tahun ini. Layaknya hp Samsung lain, perangkat satu ini juga menggunakan layar Super AMOLED dengan bentang 6,6 inci, resolusi Full HD+ dengan refresh rate 120Hz. Layar ini juga dilengkapi level brightness 1.000 nits dan teknologi Vision Booster yang memungkinkan kamu dapat tetap melihat layarnya meski berada di bawah terik sinar matahari. Terdapat tiga kamera belakang yang terdiri dari resolusi 48 MP, 8 MP ultra-wide, dan 2 MP makro. Serunya, Samsung sudah menambahkan fitur optical image stabilization (OIS) dan video digital image stabilization (VDIS). Dengan dua fitur ini, foto maupun video yang dihasilkan jauh lebih stabil. Jadi kamu tidak perlu khawatir meski saat perekaman video penuh goyangan. Prosesor MediaTek Dimensity 1080 menjadi otak semua operasional perangkat yang di sokong memori RAM 8 GB dengan tambahan hingga 8 GB mengguakan fitur RAM Plus. Untuk memori internalnya kamu bisa memilih salah satu dari dua opsi yang disediakan yaitu 128 GB dan 256 GB. Sedangkan baterainya berkapasitas 5.000mAh lengkap dengan fitur superfast charging 25W."),
        HandPhone("6", R.drawable.samsung_galaxy_a54_5g, "Samsung Galaxy A54 5G",
            "Jika mau punya hp ala-ala Galaxy S23 namun dengan harga yang lebih terjangkau kamu bisa memilih Samsung Galaxy A54 5G. Karena kamera belakangnya didesain mirip dengan hp flagship tersebut. Dimana kompartemen kameranya tidak lagi menonjol seperti generasi sebelumnya. Ada tiga kamera yang bisa kamu gunakan yaitu sensor 50 MP, ultra-wide 12 MP dan makro 5 MP. Sementara kamera depan berukuran 32 MP. Samsung juga telah meningkatkan teknologi OIS agar perekanan video lebih stabil lagi dan foto bebas blur. Layarnya pasti menggunakan panel Super AMOLED seluas 6,4 inci dengan resolusi Full HD+, refresh rate 120Hz, kecerahan 1.000 nits dan fitur Vision Booster. Di Galaxy A54 5G, Samsung lebih memilih chipset besutan besutan mereka sendiri yaitu Exynos 1380 yang akan di sokong RAM 8 GB (RAM Plus hingga 8 GB) serta memori internal 128 GB dan 256 GB. Dari sisi sumber daya ada baterai berkapasitas 5.000 mAh dengan pengisian cepat 25W. Hp Samsung terbaru ini rilis Maret 2023."),
        HandPhone("7", R.drawable.oppo_a78_5g, "Oppo A78 5G",
            "Belum lama ini OPPO merilis salah satu hp terbaru mereka dari lini A Series, yaitu OPPO A78 5G. Hp ini hadir dengan layar 6,56 inci, resolusi HD+ dan sudah mendukung refresh rate 90Hz. Layar ini bisa menjadi view finder kamera utama 50 MP yang terpasang di bagian belakang bersama kamera portrait 2 MP dan kamera depan 8 MP. Kamera ini di dukung fitur 108 MP Ultra-Clear Image yang menggunakan algoritma perangkat lunak agar perangkat dapat merekam lebih banyak detail visual dan memberikan tingkat kejernihan dengan meningkatkan resolusi kamera menjadi 108 MP. Performa OPPO A78 5G ditenagai prosesor MediaTek Dimensity 700 5G yang di sokong memori RAM 8 GB dengan teknologi RAM Expansion yang dapat memberikan RAM virtual hingga 8 GB. Sedangkan penyimpanan internal sebesar 128 GB. Untuk baterainya berkapasitas 5000 mAh dengan fitur pengisian cepat 33W SUPERVOOC Flash Charge. yang dapat mengisi baterai hingga 100% hanya dalam 67 menit"),
        HandPhone("8", R.drawable.oppo_reno8_t_5g, "Oppo Reno8 T 5G",
            "OPPO Reno8 T 5G hadir dengan layar lengkung di bagian sisinya. Panelnya berjenis AMOLED dengan bentang seluas 6,7 inci, resolusi Full HD+ serta refresh rate 120Hz.Dari sisi layar terlihat cukup menjanjikan, sehingga cocok untuk menikmati konten multimedia. Yang menarik, OPPO telah meningkatkan kapasitas resolusi kamera di hp ini. Yap, kamu akan mendapatkan kamera utama 108 MP yang akan memberikan hasil foto beresolusi tinggi. Tidak hanya itu, Reno8 T 5G juga dibekali kamera microlens 40x untuk foto objek yang tidak terlihat mata dan kamera depth 2 MP. Performa Reno8 T 5G ditenagai prosesor Snapdragon 695 5G yang dipadukan dengan RAM 8 GB (RAM virtual hingga 8 GB) dan penyimpanan internal 128 GB dan 256 GB. Hp OPPO ini disokong pengisian daya cepat 67W SUPERVOOC yang diklaim dapat mengisi baterai 100% dalam waktu 44 menit saja."),
        HandPhone("9", R.drawable.realmy_c55_nfc, "Realme C55 NFC",
            "Realme C55 NFC hadir dengan prosesor Helio G88 yang dipadukan dengan RAM 6 GB dan 8 GB serta memori internal yang berkapasitas 256 GB. Sangat cukup untuk menampung hasil foto atau video dari kamera 64 MP yang ada di bagian belakang. Kamera ini punya fitur Dynamic Image Snapshot (DIS) untuk mengambil foto yang jernih dalam situasi yang tidak stabil. Realme C55 NFC memiliki baterai besar 5000mAh lengkap bersama fitur pengisian daya 33W SUPERVOOC yang memungkinkan pengisian daya hingga 50% dalam 29 menit dan 100% dalam 63 menit."),
        HandPhone("10", R.drawable.samsung_galaxy_s23_ultra_5g, "Samsung Galaxy S23 Ultra",
            "Samsung Galaxy S23 Ultra 5G menjadi varian tertinggi, mulai dari layar yang ukurannya lebih besar seluas 6,8 inci, Dynamic AMOLED 2X beresolusi Quad HD Plus, refresh rate 120 Hz, kecerahan 1.750 nit, serta dilindungi kaca Gorilla Glass Victus 2. Yang membedakan dari dua saudaranya, Samsung Galaxy S23 Ultra dibekali S Pen bawaan yang memiliki tingkat latency 2,8 ms. Yang menarik, Galaxy S23 Ultra 5G memasang kamera utama 200 MP dengan dukungan kamera ultrawide 12 MP, kamera telefoto 10 MP dan kamera telefoto 10 MP. Banyak fitur keren dan canggih yang bisa dimanfaatkan seperti Space Zoom (100x), Astrography (memotret bintang), dan Astro Hyperlapse (memotret jejak bintang di langit). Lalu di bagian depan ada kamera selfie beresolusi 12 MP. Performanya juga diotaki prosesor Snapdragon 8 Gen 2 yang di sokong RAM 12 GB serta penyimpanan internal 256 GB, 512 GB dan 1 TB. Hp Samsung ini mendapat daya dari baterai 5.000 mAh yang mendukung pengisian cepat 45 watt."),
    )
}